### ISSUE TITLE
Spring Boot won't boot and doesn't have any output on STDOUT

### ISSUE THREAD

**Issue by 4rg0n** [roskenet/springboot-javafx-support#15]
Hello Felix,

at first: thanks for sharing your implementation of spring boot into javafx as library.

## Problem

While starting the application I see the splashscreen and that's it. There's no console output of spring booting.

**1. Problem** Application does not start
**2. Problem** There seems to be no console output

e.g. the spring logo:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.0.0.BUILD-SNAPSHOT)
```

### Debugging

Debugging showed that execution stops at booting spring context: [here](https://github.com/roskenet/springboot-javafx-support/blob/v1.3.22/src/main/java/de/felixroske/jfxsupport/AbstractJavaFxApplicationSupport.java#L60) 

### Checking for Exceptions

After debugging my first guess were ``` SpringApplication.run();``` is throwing exceptions I can't see on my console output for whatever reason. So I copied your ```AbstractJavaFxApplicationSupport``` class and let my Main class extend from this copy. Aaaand we have an output with exception now:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.0.0.BUILD-SNAPSHOT)

2017-06-09 13:33:19.838 INFO  o.s.boot.SpringApplication - Starting application on DEINEMUDDAH with PID 6768 (started by deinemuddah in D:\Projekte\java\wovdb)
2017-06-09 13:33:19.839 INFO  o.s.boot.SpringApplication - No active profile set, falling back to default profiles: default
2017-06-09 13:33:19.868 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2e99e190: startup date [Fri Jun 09 13:33:19 CEST 2017]; root of context hierarchy
2017-06-09 13:33:20.415 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-06-09 13:33:20.837 INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Building JPA container EntityManagerFactory for persistence unit 'default'
2017-06-09 13:33:21.626 INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2017-06-09 13:33:22.327 INFO  o.s.boot.SpringApplication - Started application in 2.857 seconds (JVM running for 4.585)
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at de.felixroske.jfxsupport.AbstractFxmlView.loadSynchronously(AbstractFxmlView.java:173)
	at de.felixroske.jfxsupport.AbstractFxmlView.ensureFxmlLoaderInitialized(AbstractFxmlView.java:190)
	at de.felixroske.jfxsupport.AbstractFxmlView.getView(AbstractFxmlView.java:202)
	at de.argon.wovdb.AbstractSpringJavaFxApp.showView(AbstractSpringJavaFxApp.java:149)
	at de.argon.wovdb.AbstractSpringJavaFxApp.showInitialView(AbstractSpringJavaFxApp.java:125)
	at de.argon.wovdb.AbstractSpringJavaFxApp.lambda$start$2(AbstractSpringJavaFxApp.java:93)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

I'm not sure if this exception is also thrown when using the original AbstractJavaFxApplicationSupport class.

###  Location is not set == View class can not find fxml?

After I set the location to my fxml file into the view class:

```
@FXMLView(
    value="/fxml/helloworld/helloworld.fxml"
)
``` 

I got an running Helloworld app with my copied AbstractJavaFxApplicationSupport class.
Switching back to the original AbstractJavaFxApplicationSupport class from your lib. I got the same problem again. I see the Splashscreen and no console ouput.

## Meta Info

* de.roskenet:springboot-javafx-support:1.3.22
* Spring Boot version 2.0.0-SNAPSHOT

**Comment by roskenet** [comment]
Yes, seems like it can't find your view. 
Could you provide a small (not) running example?

**Comment by 4rg0n** [comment]
# NOT running example

### Main Class
```java
package de.argon.wovdb;

import de.argon.wovdb.javafx.view.HelloworldView;
import de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WovDbSpringJavaFxApp extends AbstractJavaFxApplicationSupport
{

    public static void main(final String[] args)
    {
        launchApp(
            WovDbSpringJavaFxApp.class,
            HelloworldView.class,
            args
        );
    }
}
```

### HelloworldView

```java
package de.argon.wovdb.javafx.view;

import de.felixroske.jfxsupport.AbstractFxmlView;
import de.felixroske.jfxsupport.FXMLView;

@FXMLView(
    value="/fxml/helloworld/helloworld.fxml",
    css="/fxml/helloworld/helloworld.css",
    bundle="fxml.helloworld.helloworld"
)
public class HelloworldView extends AbstractFxmlView
{

}
```

### File Structure

![image](https://user-images.githubusercontent.com/5048544/27003249-52b899ae-4df3-11e7-8a1c-73e50d76959b.png)


# Running example

### Main Class
```java
package de.argon.wovdb;

import de.argon.wovdb.javafx.view.HelloworldView;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WovDbSpringJavaFxApp extends AbstractSpringJavaFxApp
{
    public static void main(final String[] args)
    {
        launchApp(
            WovDbSpringJavaFxApp.class,
            HelloworldView.class,
            args
        );
    }
}
```

### AbstractSpringJavaFxApp

Copied from your AbstractJavaFxApplicationSupport class.

```java
package de.argon.wovdb;

import de.felixroske.jfxsupport.*;
import javafx.application.Application;
import javafx.application.HostServices;
import javafx.application.Platform;
import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public abstract class AbstractSpringJavaFxApp extends Application
{
    private static String[] savedArgs = new String[0];

    private static Class<? extends AbstractFxmlView> savedInitialView;

    private static ConfigurableApplicationContext applicationContext;

    /** The splash screen. */
    private static SplashScreen splashScreen;

    private static List<Image> icons = new ArrayList<>();

    private final BooleanProperty appCtxLoaded = new SimpleBooleanProperty(false);

    public static Stage getStage() {
        return GUIState.getStage();
    }

    public static Scene getScene() {
        return GUIState.getScene();
    }

    public static HostServices getAppHostServices() {
        return GUIState.getHostServices();
    }

    /*
     * (non-Javadoc)
     *
     * @see javafx.application.Application#init()
     */
    @Override
    public void init() throws Exception {
        CompletableFuture.supplyAsync(() -> {
            final ConfigurableApplicationContext ctx = SpringApplication.run(this.getClass(), savedArgs);

            final List<String> fsImages = PropertyReaderHelper.get(ctx.getEnvironment(), "javafx.appicons");

            if (!fsImages.isEmpty()) {
                fsImages.forEach((s) -> icons.add(new Image(getClass().getResource(s).toExternalForm())));
            } else { // add factory images
                icons.add(new Image(getClass().getResource("/icons/gear_16x16.png").toExternalForm()));
                icons.add(new Image(getClass().getResource("/icons/gear_24x24.png").toExternalForm()));
                icons.add(new Image(getClass().getResource("/icons/gear_36x36.png").toExternalForm()));
                icons.add(new Image(getClass().getResource("/icons/gear_42x42.png").toExternalForm()));
                icons.add(new Image(getClass().getResource("/icons/gear_64x64.png").toExternalForm()));
            }
            return ctx;
        }).thenAccept(this::launchApplicationView);
    }

    /*
     * (non-Javadoc)
     *
     * @see javafx.application.Application#start(javafx.stage.Stage)
     */
    @Override
    public void start(final Stage stage) throws Exception {
        GUIState.setStage(stage);
        GUIState.setHostServices(this.getHostServices());
        final Stage splashStage = new Stage(StageStyle.UNDECORATED);

        if (AbstractSpringJavaFxApp.splashScreen.visible()) {
            final Scene splashScene = new Scene(splashScreen.getParent());
            splashStage.setScene(splashScene);
            splashStage.show();
        }

        final Runnable showMainAndCloseSplash = () -> {
            showInitialView();
            if (AbstractSpringJavaFxApp.splashScreen.visible()) {
                splashStage.hide();
                splashStage.setScene(null);
            }
        };

        synchronized (this) {
            if (appCtxLoaded.get() == true) {
                // Spring ContextLoader was faster
                Platform.runLater(showMainAndCloseSplash);
            } else {
                appCtxLoaded.addListener((ov, oVal, nVal) -> {
                    Platform.runLater(showMainAndCloseSplash);
                });
            }
        }

    }

    /**
     * Show initial view.
     */
    private void showInitialView() {
        final String stageStyle = applicationContext.getEnvironment().getProperty("javafx.stage.style");
        if (stageStyle != null) {
            GUIState.getStage().initStyle(StageStyle.valueOf(stageStyle.toUpperCase()));
        } else {
            GUIState.getStage().initStyle(StageStyle.DECORATED);
        }
        // stage.hide();

        showView(savedInitialView);
    }

    /**
     * Launch application view.
     *
     * @param ctx
     *            the ctx
     */
    private void launchApplicationView(final ConfigurableApplicationContext ctx) {
        AbstractSpringJavaFxApp.applicationContext = ctx;
        appCtxLoaded.set(true);
    }

    /**
     * Show view.
     *
     * @param newView
     *            the new view
     */
    public static void showView(final Class<? extends AbstractFxmlView> newView) {
        final AbstractFxmlView view = applicationContext.getBean(newView);

        if (GUIState.getScene() == null) {
            GUIState.setScene(new Scene(view.getView()));
        } else {
            GUIState.getScene().setRoot(view.getView());
        }
        GUIState.getStage().setScene(GUIState.getScene());

        applyEnvPropsToView();

        GUIState.getStage().getIcons().addAll(icons);
        GUIState.getStage().show();
    }

    /**
     * Apply env props to view.
     */
    private static void applyEnvPropsToView() {
        PropertyReaderHelper.setIfPresent(applicationContext.getEnvironment(), "javafx.title", String.class,
                                          GUIState.getStage()::setTitle);

        PropertyReaderHelper.setIfPresent(applicationContext.getEnvironment(), "javafx.stage.width", Double.class,
                                          GUIState.getStage()::setWidth);

        PropertyReaderHelper.setIfPresent(applicationContext.getEnvironment(), "javafx.stage.height", Double.class,
                                          GUIState.getStage()::setHeight);

        PropertyReaderHelper.setIfPresent(applicationContext.getEnvironment(), "javafx.stage.resizable", Boolean.class,
                                          GUIState.getStage()::setResizable);
    }

    /*
     * (non-Javadoc)
     *
     * @see javafx.application.Application#stop()
     */
    @Override
    public void stop() throws Exception {
        super.stop();
        if (applicationContext != null) {
            applicationContext.close();
        } // else: someone did it already
    }

    /**
     * Sets the title. Allows to overwrite values applied during construction at
     * a later time.
     *
     * @param title
     *            the new title
     */
    protected static void setTitle(final String title) {
        GUIState.getStage().setTitle(title);
    }

    /**
     * Launch app.
     *
     * @param appClass
     *            the app class
     * @param view
     *            the view
     * @param args
     *            the args
     */
    public static void launchApp(final Class<? extends AbstractSpringJavaFxApp> appClass,
                                 final Class<? extends AbstractFxmlView> view, final String[] args) {
        launchApp(appClass, view, new SplashScreen(), args);
    }

    /**
     * Launch app.
     *
     * @param appClass
     *            the app class
     * @param view
     *            the view
     * @param splashScreen
     *            the splash screen
     * @param args
     *            the args
     */
    public static void launchApp(final Class<? extends AbstractSpringJavaFxApp> appClass,
                                 final Class<? extends AbstractFxmlView> view, final SplashScreen splashScreen, final String[] args) {
        savedInitialView = view;
        savedArgs = args;

        if (splashScreen != null) {
            AbstractSpringJavaFxApp.splashScreen = splashScreen;
        } else {
            AbstractSpringJavaFxApp.splashScreen = new SplashScreen();
        }
        Application.launch(appClass, args);
    }
}
```

**Rest is the same as in the not running example**

**Comment by roskenet** [comment]
I would rather prefer a git repo that I can clone.

Why don't you extend WovDbSpringJavaFxApp from AbstractJavaFxApplicationSupport?

**Comment by 4rg0n** [comment]
I just tried to extend WovDbSpringJavaFxApp from AbstractJavaFxApplicationSupport. 
Results in a not running application with no STDOUT output. So the same as I would directly extend my Main class from your AbstractJavaFxApplicationSupport.

Just sent you a mail to your homepage email address.

**Comment by roskenet** [comment]
Problem is addressed in new ticket:
https://github.com/roskenet/springboot-javafx-support/issues/16
