### ISSUE TITLE
Fails to load when running jar directly

### ISSUE THREAD

**Issue by hzamir** [roskenet/springboot-javafx-support#29]
I have been unable to run jar directly, though running it via maven with the spring-boot:run target works fine (or running via ide). The stack trace is as follows. Not that while the message ostensibly complains about not loading the spring application context, see the "Not on FX Application Thread" message further down.

E 23:36:04.145 ort.AbstractJavaFxApplicationSupport - Failed to load spring application context: 
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException: null
        at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$null$0(AbstractJavaFxApplicationSupport.java:105)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(AbstractJavaFxApplicationSupport.java:105)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        ... 5 common frames omitted
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.stage.Window.setShowing(Window.java:921)
        at javafx.stage.Window.hide(Window.java:947)
        at com.sun.javafx.stage.WindowPeerListener.closed(WindowPeerListener.java:100)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:119)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:151)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
        at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
        at com.sun.glass.ui.Window.notifyDestroy(Window.java:1183)

**Comment by roskenet** [comment]
Has never happened before...
Could you please provide a stripped down example?
Are you able to run the examples from
https://github.com/roskenet/spring-javafx-examples ?

**Comment by hzamir** [comment]
I will try a little later. I am building on OS X 10.11.6. I tried with java version "1.8.0_144".

**Comment by hzamir** [comment]
I tried stepping through and found that I after stripping everything out I could even reproduce the issue running the mvn spring-boot:run target as well. I'm not sure why your examples seem to run and mine don't when stripped down to be equivalent, but... 

The Spring ApplicationContext is initialized fine, but the falure occurs when adding the gear icons, 
( AbstractJavaFxApplicationSupport.java line 105: fsImages.forEach((s) -> icons.add(new Image(getClass().getResource(s).toExternalForm())));

)
which in turn prevents the context from being returned.

**Comment by hzamir** [comment]
After much debugging, I have found what appears to be the real issue, though I believe that I uncovered a separate issue when icon loading fails (I include the code below, but I will send you a pull request).

I had two issues, neither of which caused a problem when running mvn spring-boot:run target, only when directly running the jar:
1. My fmxl file was named Foo.fxml instead of foo.fxml this prevented the bean from loading
2. My initial issue was my custom icon had no path, and specify "/com/mycompany/mypackage/myfile.png"

My recommended fix for the Not an Fx Application thread is:


  private void loadIcons(ConfigurableApplicationContext ctx)
  {
    try {
      final List<String> fsImages = PropertyReaderHelper.get(ctx.getEnvironment(), "javafx.appicons");

      if (!fsImages.isEmpty()) {
        fsImages.forEach((s) ->
            {
              Image img =  new Image(getClass().getResource(s).toExternalForm());
              icons.add(img);
            }
        );
      } else { // add factory images
        icons.add(new Image(getClass().getResource("/icons/gear_16x16.png").toExternalForm()));
        icons.add(new Image(getClass().getResource("/icons/gear_24x24.png").toExternalForm()));
        icons.add(new Image(getClass().getResource("/icons/gear_36x36.png").toExternalForm()));
        icons.add(new Image(getClass().getResource("/icons/gear_42x42.png").toExternalForm()));
        icons.add(new Image(getClass().getResource("/icons/gear_64x64.png").toExternalForm()));
      }
    } catch (Exception e) {
      LOGGER.error("Failed to load icons: ", e);
    }


  }
  /*
   * (non-Javadoc)
   *
   * @see javafx.application.Application#init()
   */
  @Override
  public void init() throws Exception
  {
    CompletableFuture.supplyAsync(() -> {
     return SpringApplication.run(this.getClass(), savedArgs);
    }).whenComplete((ctx, throwable) -> {
      if (throwable != null) {
        LOGGER.error("Failed to load spring application context: ", throwable);
        Platform.runLater(() -> showErrorAlert(throwable));
      } else {
        Platform.runLater(() -> {
          loadIcons(ctx);
          launchApplicationView(ctx);});
      }
    });
  }

**Comment by roskenet** [comment]
Cool! Alright!
Thanks!
