### ISSUE TITLE
java.lang.ClassCastException when using non-string properties

### ISSUE THREAD

**Issue by raworre** [roskenet/springboot-javafx-support#5]
This may just be how I am using the API, but currently when I try to use javafx.* properties I get a ClassCastException thrown from PropertyReaderHelper#setIfPresent

For example, my application.yaml looks like this
```
javafx:
    stage:
        resizable: false
```

I get the following error when trying to create the stage
```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport$$Lambda$142/489220484.accept(Unknown Source)
	at de.felixroske.jfxsupport.PropertyReaderHelper.setIfPresent(PropertyReaderHelper.java:35)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showView(AbstractJavaFxApplicationSupport.java:141)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showInitialView(AbstractJavaFxApplicationSupport.java:105)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$start$2(AbstractJavaFxApplicationSupport.java:76)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport$$Lambda$101/1446651899.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/255090923.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/846097765.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/1314856651.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

This also happens when trying to use application.properties file with this format:
```
javafx.stage.resizable=false
```

**Comment by raworre** [comment]
I am currently using version 1.3.15

**Comment by roskenet** [comment]
Oh... Thanks for reporting.

**Comment by raworre** [comment]
Verified this is working. Pulled down 1.3.16 and can now set javafx.* properties. Thanks for the quick response!
