### ISSUE TITLE
Build with maven

### ISSUE THREAD

**Issue by beta3000** [roskenet/springboot-javafx-support#6]
When execute my project in intellij Idea run fine, but  then build my project with maven and execute i get this error. Only show the splash screen.

Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at de.felixroske.jfxsupport.AbstractFxmlView.loadSynchronously(AbstractFxmlView.java:99)
	at de.felixroske.jfxsupport.AbstractFxmlView.ensureFxmlLoaderInitialized(AbstractFxmlView.java:113)
	at de.felixroske.jfxsupport.AbstractFxmlView.getView(AbstractFxmlView.java:125)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showView(AbstractJavaFxApplicationSupport.java:117)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showInitialView(AbstractJavaFxApplicationSupport.java:105)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$start$2(AbstractJavaFxApplicationSupport.java:76)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by beta3000** [comment]
I change mi view from Proyecto.fxml to proyecto.fxml, capital letter was the problem.

**Comment by roskenet** [comment]
Thanks.
I am thinking about whether we should make this case insensitive.
But by now, I close this, alright?

**Comment by beta3000** [comment]
Yes work fine now, thanks for springboot-javafx-support.
Regards
