### ISSUE TITLE
de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport - Failed to load spring application context: 

### ISSUE THREAD

**Issue by hawskpy** [roskenet/springboot-javafx-support#92]
15:35:16.316 [ForkJoinPool.commonPool-worker-19] ERROR de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport - Failed to load spring application context: 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:437)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:419)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:268)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:249)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(AbstractJavaFxApplicationSupport.java:94)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 common frames omitted

What's the reason?I tried to run it in JDK -11.0.10.9-hotspot, and Javafx 17 in IDE. The project works, but it doesn't work when packaged.

I tried to solve the problem, but I had no idea.

**Comment by sangjiexun** [comment]
Me too

**Comment by zzqo** [comment]
Me too
